littlelimon/urls.py
from django.contrib import admin
from django.urls import path, include
from restaurant import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('book/', views.BookView.as_view(), name='book'),
    path('menu/', views.menu, name='menu'),
    path('bookings/', views.bookingView, name='bookings'),
    path('api/', include('restaurant.urls'))
]

restaurant/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views


router = DefaultRouter()
router.register('bookings', views.ReservationsApi, basename='bookings')
router.register('menu', views.MenuApiView, basename='menu')
router.register('cart', views.CartApiView, basename='cart')
router.register('orders', views.OrdersApiView, basename='orders')
router.register('order-items', views.OrderItemApiView, basename='order-items')
urlpatterns = [
    path('', include('djoser.urls')),
    path('', include('djoser.urls.authtoken')),
    path('', include(router.urls)),
]

restaurant/models.py
from django.db import models
from django.contrib.auth.models import User

class Menu(models.Model):
    """ class for the Menu"""
    menuItem = models.CharField(max_length=200, null=False)
    description = models.CharField(max_length=500, null=False)
    price = models.IntegerField(null=False)

    def __str__(self):
        """ string representation item: 5$ """
        return self.menuItem + ': ' + str(self.price) + '$'

class Bookings(models.Model):
    """ class for bookings """
    name = models.CharField(max_length=200)
    slots = models.IntegerField(default=2)
    date = models.DateField(null=False)

    def __str__(self):
        """ string booking name: name """
        return 'booking name: '+ self.name

class Cart(models.Model):
    """ cart """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    totalprice = models.DecimalField(decimal_places=2, max_digits=65)

    def __str__(self):
        """ cart representation """
        return 'cart for: ' + str(self.user)

class Orders(models.Model):
    """ Order """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order')
    crew_member = models.ForeignKey(User, on_delete=models.CASCADE, related_name='crew', default=2)
    status = models.BooleanField(default=False)
    totalPrice = models.DecimalField(decimal_places=2, max_digits=65)
    def __str__(self):
        """ string related user name """
        return 'order by: ' + str(self.user)

class OrderItem(models.Model):
    """ orderItem """
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, related_name='orderItem')
    item = models.ForeignKey(Menu, on_delete=models.CASCADE) 
    quentity = models.IntegerField()
    totalPrice= models.DecimalField(max_digits=65 ,decimal_places=2)

    def __str__(self):
        """ string order number: order """
        return str(self.order)

restaurant/forms.py
from django import forms
from .models import Bookings

class BookingForm(forms.ModelForm):
    """ form for bookings """
    class Meta:
        model = Bookings
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'please enter your name', 'class': 'form-control'}),
            'slots': forms.NumberInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control date'})
        }
        

restaurant/views.py
from django.shortcuts import render
from django.views import View
from restaurant.forms import BookingForm
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json
from .models import Bookings, Menu, Cart, Orders, OrderItem
from .serializers import BookingsSerializers, MenuSerializer,\
CartSerializers, OrderSerializers, OrderItemSerializers
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action, permission_classes
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.models import User, Group
from django.shortcuts import get_object_or_404


# views here.
def home(request):
    """ view function for home page """
    return render(request, 'index.html')

def menu(request):
    """ return menu page """
    menu = Menu.objects.all()
    context = {'menu': menu}
    return render(request, 'menu.html', context)

class BookView(View):
    """ class for booking tempates """
    def get(self, request):
        """ display booking page """
        form = BookingForm()
        context = {'form': form}
        return render(request, 'book.html', context)
    def post(self, request):
        """ post booking data"""
        data = json.load(request)
        form = BookingForm(data)
        if form.is_valid():
            form.save()
            return HttpResponse('success')
        else:
            return HttpResponse(status=400)
        
def bookingView(request):
    """ display all bookings """
    bookings = Bookings.objects.all()
    context = {'bookings': bookings}
    return render(request, 'booking.html', context)

""" API Views """
class ReservationsApi(viewsets.ViewSet):
    """ display api """
    def list(self, request):
        """ list all bookings """
        query_set = Bookings.objects.all()
        serializer = BookingsSerializers(query_set, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk):
        """ retrieve one booking item """
        query_set = Bookings.objects.get(id=pk)
        serializer = BookingsSerializers(query_set)
        return Response(serializer.data)
    
    @action(detail=False, methods=['DELETE'])
    def delete(self, request, pk):
        """ delete booking item"""
        booking = Bookings.objects.get(id=pk)
        booking.delete()
        return Response('booking got canceled')

    @action(detail=False, methods=['POST'])
    def post(self, request):
        """ function to create booking through API """
        serializer = BookingsSerializers(data=request.data)
        if serializer.is_valid():
            booking = Bookings.objects.create(
                name = serializer.validated_data['name'],
                date = serializer.validated_data['date'],
                slots = serializer.validated_data['slots']
            )
            booking.save()
            return Response(serializer.data)

class MenuApiView(viewsets.ViewSet):
    """ class to view menu items and post to it"""
    def list(self, request):
        """ list Menu items """
        query_set = Menu.objects.all()
        serializer = MenuSerializer(query_set, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk):
        """ retrieve one menu item """
        query_set = Menu.objects.get(id=pk)
        serializer = MenuSerializer(query_set)
        return Response(serializer.data)

    @action(detail=False, methods=['DELETE'])
    def delete(self, request, pk):
        """ delete menu item"""
        item = Menu.objects.get(id=pk)
        item.delete()
        return Response('item got deleted')

    @action(detail=False, methods=['POST'])
    def post(self, request):
        """ function to add menu items """
        serializer = MenuSerializer(data=request.data)
        if serializer.is_valid():
            menu = Menu(
                menuItem = serializer.validated_data['menuItem'],
                description = serializer.validated_data['description'],
                price = serializer.validated_data['price']
            )
            menu.save()
            return Response(serializer.data)

@permission_classes([IsAuthenticated])
class CartApiView(viewsets.ViewSet):
    """ list cart and post to cart """
    def list(self, request):
        query_set = Cart.objects.filter(user=request.user).all()
        serializer = CartSerializers(query_set, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['POST'])
    def post(self, request):
        """ post to cart """
        user_id = request.user.id
        data = request.data
        item_id = data['item']
        quantity = data['quantity']
        item = get_object_or_404(Menu, id=item_id)
        price = item.price
        totalprice = price * quantity
        data['totalprice'] = totalprice
        data['user'] = user_id
        data['item'] = item_id
        serializer = CartSerializers(data=data)
        if serializer.is_valid():
            cart = Cart.objects.create(
                item = serializer.validated_data['item'],
                user = serializer.validated_data['user'],
                quantity = serializer.validated_data['quantity'],
                totalprice = serializer.validated_data['totalprice']
            )
            cart.save()
            return Response(serializer.data)
        else:
            errors = serializer.errors
            print(errors)
            return Response('not valid')

@permission_classes([IsAuthenticated])
class OrdersApiView(viewsets.ViewSet):
    """ 
    class to place orders
    orders are created and orderItems related also
    """
    def list(self, request):
        """ list all orders """
        if request.user.groups.filter(name='Maneger').exists():
            orders = Orders.objects.all()
        else:
            user_id = request.user.id
            orders = Orders.objects.filter(user=get_object_or_404(User, id=user_id)).all()
        serializer = OrderSerializers(orders, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['POST'])
    def post(self, request):
        """ create orders """
        user_id = request.user.id
        user = get_object_or_404(User, id=user_id)
        cart = Cart.objects.filter(user=user).all()
        """ create order """
        sum = 0
        for item in cart:
            sum += item.totalprice
        order = Orders.objects.create(
            user = user,
            totalPrice = sum
        )
        order.save()
        """ create order items  and relate them to order created """
        for element in cart:
            order_item = OrderItem.objects.create(
                order = order,
                item = element.item,
                quentity = element.quantity,
                totalPrice = element.totalprice
            )
            order_item.save()
        
        """ delete cart objects """
        cart = Cart.objects.filter(user=user_id).delete()
        """ display order created """
        serializer = OrderSerializers(order)
        return Response(serializer.data)

    def partial_update(self, request, *args, **kwargs):
        """ manager updates the crew """
        if request.user.groups.filter(name='Maneger').exists():
            instance = get_object_or_404(Orders, id=self.kwargs['pk'])
            serializer = OrderSerializers(instance, data=request.data, partial=True)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data)
        else:
            return Response('unauthorized', 403)
    
    @action(detail=False, methods=['DELETE'])
    def delete(self, request, pk=None):
        """ user wants to delete his order """
        order = get_object_or_404(Orders, id=pk)
        user = order.user
        user_id = user.id
        if request.user.groups.filter(name='Maneger').exists() \
or request.user.id == user_id:
            order.delete()
            return Response('order got cancelled')
        else:
            return Response('unauthorized', 403)        
    
@permission_classes([IsAuthenticated])
class OrderItemApiView(viewsets.ViewSet):
    """ list order items """
    def list(self, request):
        user = get_object_or_404(User, id=request.user.id)
        orders = user.order.all()
        items = []
        for order in orders:
            items.extend(order.orderItem.all())
        serializer = OrderItemSerializers(items, many=True)
        return Response(serializer.data)

restaurant/templates/book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <title>Document</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
</head>
<body>
    <header>
        <img src="{% static 'img/logo.png' %}" />
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'menu' %}">Menu</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
        </ul>
    </nav>
    <section class="book_body">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn" id="bookingbtn"> confirm booking </button>
        </form>
    </section>
    <footer>
        <article>
            <img src="{% static 'img/logo_footer.png' %}" />
        </article>
        <article>
            <p>Copyright {{ current_year }} Little Lemon</p>
        </article>
    </footer>
    <script>
        $(document).ready(function () {
            $('.date').attr('type', 'date')
        });
        $('#bookingbtn').click(function (e){
            e.preventDefault();
            const csrftoken = $('[name="csrfmiddlewaretoken"]').val();
            const name = $('#id_name').val();
            const date = $('#id_date').val();
            const slots = $('#id_slots').val();
            dateInserted = new Date(date)
            todayDate = new Date()
            if (todayDate > dateInserted) {
                alert('not valid date');
                return;
            }
            data = {
                'name': name,
                'date': date,
                'slots': slots
            };
            fetch("{% url 'book' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify(data),
            }).then(res => res.text()).then(data => {
                if (data === 'success') {
                    alert('booking is confirmed.')
                }
            })
            })
    </script>
</body>
</html>

restaurant/templates/booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <title>Document</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
</head>
<body>
    <header>
        <img src="{% static 'img/logo.png' %}" />
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'menu' %}">Menu</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
        </ul>
    </nav>
    <section id="bookings">
        <div class="containter">
            <div class="row">
                {% for booking in bookings %}
                <div class="col-mid-4">
                    <p>reservation's name: {{ booking.name }}</p>
                    <p>date: {{ booking.date }}</p>
                    <p>slots for: {{ booking.slots }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <footer>
        <article>
            <img src="{% static 'img/logo_footer.png' %}" />
        </article>
        <article>
            <p>Copyright {{ current_year }} Little Lemon</p>
        </article>
    </footer>
</body>
</html>

restaurant/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
<header>
  <img src="{% static 'img/logo.png' %}" />
</header>
    <nav>
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="{% url 'menu' %}">Menu</a></li>
        <li><a href="{% url 'book' %}">Book</a></li>
      </ul>
  </nav>
<body>
<section>
    <article id="hero">
      <h1 class="heading_shadow">SPECIAL OFFER</h1>
      <p>
        30% Off This Weekend 
      </p>
      <a href="#" class="cta"> Book now </a>
    </article>
  </section>
  <section>
    <article>
      <h2>Our New Menu</h2>
      <img src="{% static 'img/grill.jpg' %}">
      <p>
        Our menu consists of 12-15 seasonal items based on Italian, Greek, and Turkish culture.
      </p>
      <p>
        <a href="#">See our new menu</a>
      </p>
    </article>
    <article>
      <h2>Book a table</h2>
      <img src="{% static 'img/salad.jpg' %}">
      <p>
        Reserve your table for an Italian, Greek, and Turkish dining experience.
      </p>
      <p>
        <a href="#">Book your table now</a>
      </p>
    </article>
    <article>
      <h2>Opening Hours</h2>
      <img src="{% static 'img/head_chef.jpg' %}">
      <p>
        The Little Lemon Restaurant is open 7 days a week, except for public holidays. 
      </p>
      <ul>
        <li>Mon - Fri: 2pm - 10pm</li>
        <li>Sat: 2pm - 11pm</li>
        <li>Sun: 2pm - 9pm</li>
      </ul>
    </article>
  </section>
  <footer>
    <article>
      <img src="{% static 'img/logo_footer.png' %}" />
    </article>
    <article>
      <p>Copyright {{ current_year }} Little Lemon</p>
    </article>
  </footer>
</body>
</html>

restaurant/templates/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <title>Document</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
</head>
<body>
    <header>
        <img src="{% static 'img/logo.png' %}" />
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Menu</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
        </ul>
    </nav>
    <section class="container">
      <div class="row">
        {% for item in menu %}
        <div class="col-md-6">
          <p>{{ item.menuItem }}: {{item.price}}$</p>
        </div>
        {% endfor %}
      </div>
    </section>
    <footer>
        <article>
            <img src="{% static 'img/logo_footer.png' %}" />
        </article>
        <article>
            <p>Copyright {{ current_year }} Little Lemon</p>
        </article>
    </footer>
</body>
</html>